Added Markup and Additional Webpages
INF6420/ss22-ha7791 pull request #3
Opened 2022-06-03 03:54 UTC by ha7791

2022-06-03 23:15 UTC, axamei requested changes
Hi @ha7791 there are a few headings being used incorrectly. Please review the comments and update the pull request to include the requested changes.

2022-06-03 23:15 UTC, axamei commented on wireframes/footer.html
> +<!-- While researching, I learned that both my navigation bar and footer would need to have their own files. -->
This is true if we were using other frameworks or languages that allow for templating. Since we are using plain HTML, we will have to keep them as sections on each static site instead of separate files.

2022-06-03 23:15 UTC, axamei commented on wireframes/about.html
> +        <h2>Bio</h2>
Use headings to communicate content hierarchy and structure and not for font sizing. Read: https://www.a11yproject.com/posts/how-to-accessible-heading-structure/

2022-06-03 23:15 UTC, axamei commented on wireframes/contacts.html
> +        <h3>Contact</h3>
Use headings to communicate content hierarchy and structure and not for font sizing. Read: https://www.a11yproject.com/posts/how-to-accessible-heading-structure/

2022-06-03 23:15 UTC, axamei commented on wireframes/gallery.html
> +              <button>Character Designs</button>
If you would like a gallery or carousel for the final project, we can discuss how to best implement it. Right now I am unclear what the buttons are intended to do.

2022-06-13 15:18 UTC, ha7791 commented on wireframes/about.html
> +        <h2>Bio</h2>
Whoops.

2022-06-13 15:21 UTC, ha7791 commented on wireframes/gallery.html
> +              <button>Character Designs</button>
I did an awful job of explaining it on my gallery wireframe. lol 

Basically, I looked at some art websites, used Inspect Element, and noticed they used button tags for their gallery navbar. How that works goes waaay over my head right now, but it basically lets you click on a button, highlights it, and then the gallery content changes based on what you clicked without leaving the current webpage. I hope that makes sense; I'm still learning the lingo... lol

Example: https://www.artstation.com/?sort_by=community (the row that says "Channels")

2022-06-13 15:26 UTC, ha7791 commented
> Hi @ha7791 were you able to make the changes requested?

Yes. I have to get in the habit of checking this site more lol. I just noticed these requests this morning

2022-06-13 15:28 UTC, merged